version: '3.7'

services:
  hypatos_challenge:
    container_name: hypatos_challenge
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
